(source gnu)
(source melpa)

(depends-on "flycheck")
(depends-on "feature-mode")
(depends-on "groovy-mode")
(depends-on "csv-mode")
(depends-on "jedi")
(depends-on "jedi-direx")
(depends-on "auto-complete")
(depends-on "pdf-tools")
