#!/bin/bash

cd "${HOME}"

# load the default env
source "${HOME}/.shrc_var"

# For flash to be fully functionnal
export GDK_NATIVE_WINDOWS=1
export PATH="$(dirname "$0")/bin:$(dirname "$0")/devel_bin:$PATH"

pkill -9 fluxbox

fluxbox &

fbpid=$!

volti &

numlockx
konix_notify_daemon > ~/.notify_daemon_log 2>&1 &

sleep 4
{
    killall conky
    wicd-gtk -t &
    conky -d -c ~/.conky.d/conky1 > ~/conky.log 2> ~/conky.err
	pcmanfm --desktop & # nice and simple desktop manager
	# start de emacs_tray_daemon if possible
	emacs_tray_daemon.py &
	konix_mail_tray_daemon.py &
} &

if [ -n "$KONIX_X_INIT" ]
then
	eval "$KONIX_X_INIT"
fi

wait $fbpid
