#!/bin/bash

fluxbox &

fbpid=$!


#gnome-terminal --maximize &
guake &
numlockx
sleep 4
{
    killall conky
    Thunar --daemon &
    nm-applet &
    idesk &
    conky -d -c ~/.conky.d/conky1
} &

{
	sleep 20
	xmodmap /home/snake/.fluxbox/xmod_swap_caps_lock
	}

wait $fbpid
