#!/usr/bin/env bash

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SELF_DIR}/_find_completion.sh"
_comp="$(_find_completion docker)" && source "$_comp" || return

ME="$(basename "${BASH_SOURCE[0]}")"

_de () {
    # take the words without the initial de and substitute it with "docker run -ti --rm"
    COMP_WORDS=(docker exec -ti "${COMP_WORDS[@]:1}")
    # then, add 2 to cword because I added 3 words (actually removed 1 and
    # added 3, but who cares?)
    COMP_CWORD=$((COMP_CWORD + 2))
    # then, update the line and the point,
    COMP_LINE=${COMP_LINE/de/docker exec -ti}
    COMP_POINT=$((COMP_POINT + 17)) # "docker exec -it" contains 13 characters more than "de"
    __start_docker
}

complete -F _de "${ME}"
