#!/usr/bin/env bash

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SELF_DIR}/_find_completion.sh"
_comp="$(_find_completion docker)" && source "$_comp" || return

ME="$(basename "${BASH_SOURCE[0]}")"

_dr () {
    # take the words without the initial dr and substitute it with "docker run -ti --rm"
    COMP_WORDS=(docker run -ti --rm "${COMP_WORDS[@]:1}")
    # then, add 3 to cword because I added 3 words (actually removed 1 and
    # added 4, but who cares?)
    COMP_CWORD=$((COMP_CWORD + 3))
    # then, update the line and the point,
    COMP_LINE=${COMP_LINE/dr/docker run -ti --rm}
    COMP_POINT=$((COMP_POINT + 17)) # "docker run -ti --rm" contains 17 characters more than "dr"
    __start_docker
}

complete -F _dr "${ME}"
