#!/bin/bash

source /usr/share/bash-completion/completions/docker

ME="$(basename "${BASH_SOURCE[0]}")"

_dr () {
    # take the words without the initial dr and substitute it with "docker run -ti --rm"
    COMP_WORDS=(docker run -ti --rm "${COMP_WORDS[@]:1}")
    # then, add 3 to cword because I added 3 words (actually removed 1 and
    # added 4, but who cares?)
    COMP_CWORD=$((COMP_CWORD + 3))
    # then, update the line and the point,
    COMP_LINE=${COMP_LINE/dr/docker run -ti --rm}
    COMP_POINT=$((COMP_POINT + 17)) # "docker run -ti --rm" contains 17 characters more than "dr"
    _docker
}

complete -F _dr "${ME}"
