#!/usr/bin/env bash
# No set -eu here: this file is sourced into the interactive shell

source <(kubectl completion bash)
ME="$(basename "${BASH_SOURCE[0]}")"

complete -o default -F __start_kubectl "${ME}"
