#!/usr/bin/env bash
# No set -eu here: this file is sourced into the interactive shell

ME="$(basename "${BASH_SOURCE[0]}")"
COMPLETION_SCRIPT="${HOME}/.nix-profile/share/bash-completion/completions/${ME}.bash"

source "${COMPLETION_SCRIPT}"
