#!/usr/bin/env bash
# No set -eu here: this file is sourced into the interactive shell

ME="$(basename "${BASH_SOURCE[0]}")"
source <(${ME} completion bash)
complete -o default -o nospace -F __start_ory orye2e
