#!/bin/bash

COMPLETION_SCRIPT="${TMPDIR}/rclone_completer_script.sh"

if ! test -e "${COMPLETION_SCRIPT}"
then
    rclone genautocomplete bash - > "${COMPLETION_SCRIPT}"
fi

source "${COMPLETION_SCRIPT}"
