#!/usr/bin/env bash

ME="$(basename "${BASH_SOURCE[0]}")"
SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SELF_DIR}/_find_completion.sh"
_comp="$(_find_completion apt)" && source "$_comp" || return

_sa () {
    COMP_WORDS=(sudo apt "${COMP_WORDS[@]:1}")
    COMP_CWORD=$((COMP_CWORD + 1))
    COMP_LINE=${COMP_LINE/sa /sudo apt }
    COMP_POINT=$((COMP_POINT + 6))
    _apt
}

complete -F _sa "${ME}"
