#!/bin/bash

ME="$(basename "${BASH_SOURCE[0]}")"
source /usr/share/bash-completion/completions/apt

_sap () {
    # take the words without the initial sap and substitute it with "sudo apt purge"
    COMP_WORDS=(sudo apt purge "${COMP_WORDS[@]:1}")
    # then, add 2 to cword because I added two words (actually removed 1 and
    # added 3, but who cares?)
    COMP_CWORD=$((COMP_CWORD + 2))
    # then, update the line and the point,
    COMP_LINE=${COMP_LINE/sap/sudo apt purge}
    COMP_POINT=$((COMP_POINT + 11)) # sudo apt purge contains 11 characters more than sap
    _apt
}

complete -F _sap "${ME}"
