#!/bin/bash

if test -e "${KONIX_DEVEL_DIR}/sjoubert_dot_rc/.config/bash/completions/aptitude"
then
    source "${KONIX_DEVEL_DIR}/sjoubert_dot_rc/.config/bash/completions/aptitude"
	complete -F _sar sap
else
    konix_display.py "Could not load aptitude completion from sjoubertrc"
fi
