#!/usr/bin/env bash
# No set -eu here: this file is sourced into the interactive shell

source /usr/share/bash-completion/completions/systemctl
ME="$(basename "${BASH_SOURCE[0]}")"
complete -F _systemctl "${ME}"
