import dracula.draw

# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

dracula.draw.blood(c, {
    'spacing': {
        'vertical': 6,
        'horizontal': 8
    }
})

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

config.set("editor.command", ["ec", "{file}"])
config.set("completion.cmd_history_max_items", -1)
config.set("completion.use_best_match", True)

# Bindings for normal mode
config.bind('Uc', 'set network user-agent "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36"')
config.bind('Ud', 'set network user-agent ""')
config.bind('Uf', 'set network user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"')

config.unbind('d', mode='normal')
config.bind('dd', 'tab-close')
config.bind('dsD', 'spawn -u konix_qutebrowser_web_search.sh -d')
config.bind('dsS', 'spawn -u konix_qutebrowser_web_search.sh')
config.bind('dsd', 'spawn -u konix_qutebrowser_web_search.sh -dc')
config.bind('dss', 'spawn -u konix_qutebrowser_web_search.sh -c')
config.bind('sp', 'spawn -u konix_qutebrowser_password.sh')
config.bind('yas', 'spawn -u konix_qutebrowser_ril_save_url.sh')
config.bind('ye', 'spawn -u konix_qutebrowser_edit_emacs.sh -c')
config.bind('zc', 'spawn -u konix_qutebrowser_open_with_chromium.sh')
config.bind('zf', 'spawn -u konix_qutebrowser_open_with_firefox.sh')
config.bind('yE', 'spawn -u konix_qutebrowser_edit_content.sh')
config.bind('dw', 'spawn -u konix_qutebrowser_dwim.sh')
config.bind('<ctrl-alt-s>', 'spawn -u konix_qutebrowser_toggle_autoscroll.sh')
config.bind('ss', 'spawn -u konix_qutebrowser_toggle_autoscroll.sh')
config.bind('<ctrl-alt-up>',   'spawn -u konix_qutebrowser_decr_autoscroll.sh')
config.bind('<ctrl-alt-down>', 'spawn -u konix_qutebrowser_incr_autoscroll.sh')
config.bind('s-',   'spawn -u konix_qutebrowser_decr_autoscroll.sh')
config.bind('s+', 'spawn -u konix_qutebrowser_incr_autoscroll.sh')
config.bind('Sb', 'open qute://bookmarks#bookmarks')
config.bind('SB', 'open qute://bindings')
config.bind('Sm', ':messages')
config.bind('<ctrl-n>', 'spawn -u konix_qutebrowser_emacs_org_add_roam_note.sh')
config.bind('<ctrl-alt-n>', 'spawn -u konix_qutebrowser_emacs_org_add_roam_capture.sh')
config.bind('<ctrl-shift-n>', 'spawn -u konix_qutebrowser_emacs_org_add_quote_at_point.sh')
# config.bind('<alt-n>', 'spawn -u konix_qutebrowser_emacs_org_add_note.sh')
# config.bind('<alt-shift-n>', 'spawn -u konix_qutebrowser_emacs_org_add_todo.sh')
config.bind('<ctrl-m>', 'spawn -u konix_qutebrowser_yank_bib.sh')
config.bind('<alt-n>', """:jseval (function(){window.hypothesisConfig=function(){return{showHighlights:true,appType:'bookmarklet'};};var d=document,s=d.createElement('script');s.setAttribute('src','https://hypothes.is/embed.js');d.body.appendChild(s)})();""")
config.bind('<alt-shift-n>', """:open https://via.hypothes.is/{url}""")
