import os
from pathlib import Path

import dracula.draw

# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
config.load_autoconfig()

dracula.draw.blood(c, {'spacing': {'vertical': 6, 'horizontal': 8}})

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

config.set("editor.command", ["ec", "{file}"])
config.set("completion.cmd_history_max_items", -1)
config.set("completion.use_best_match", True)
config.set("content.user_stylesheets", [
    str(
        Path(os.environ["KONIX_PERSO_CONFIG_DIR"]) /
        "qutebrowser/konubinix.css"),
])

config.unbind('d', mode='normal')
config.bind('dd', 'tab-close')
config.bind('dg', 'tab-give')
config.bind('pi', 'spawn -u konix_qutebrowser_print_ipfa.sh')
config.bind('yi', 'spawn -u konix_qutebrowser_ipfa.sh')
config.bind('dsD', 'spawn -u konix_qutebrowser_web_search.sh -d')
config.bind('dsS', 'spawn -u konix_qutebrowser_web_search.sh')
config.bind('dsd', 'spawn -u konix_qutebrowser_web_search.sh -dc')
config.bind('dss', 'spawn -u konix_qutebrowser_web_search.sh -c')
config.bind('sp', 'spawn -u konix_qutebrowser_password.sh')
config.bind('yas', 'spawn -u konix_qutebrowser_ril_save_url.sh')
config.bind('ye', 'spawn -u konix_qutebrowser_edit_emacs.sh -c')
config.bind('zc', 'spawn -u konix_qutebrowser_open_with_chromium.sh')
config.bind('zf', 'spawn -u konix_qutebrowser_open_with_firefox.sh')
config.bind('yE', 'spawn -u konix_qutebrowser_edit_content.sh')
config.bind('dw', 'spawn -u konix_qutebrowser_dwim.sh')
config.bind('ss', 'spawn -u konix_qutebrowser_scroll.sh')
config.bind('Sb', 'open qute://bookmarks#bookmarks')
config.bind('SB', 'open qute://bindings')
config.bind('Sm', ':messages')
config.bind('<ctrl-n>',
            'spawn -u konix_qutebrowser_emacs_org_add_roam_note.sh')
config.bind('<ctrl-alt-n>',
            'spawn -u konix_qutebrowser_emacs_org_add_roam_capture.sh')
config.bind('<ctrl-shift-n>',
            'spawn -u konix_qutebrowser_emacs_org_add_quote_at_point.sh')
config.bind('<ctrl-e>', 'konix_qutebrowser_emacs_everywhere.sh')
# config.bind('<alt-n>', 'spawn -u konix_qutebrowser_emacs_org_add_note.sh')
# config.bind('<alt-shift-n>', 'spawn -u konix_qutebrowser_emacs_org_add_todo.sh')
config.bind('<ctrl-m>', 'spawn -u konix_qutebrowser_yank_bib.sh')
config.bind(
    '<alt-n>',
    """:jseval (function(){window.hypothesisConfig=function(){return{showHighlights:true,appType:'bookmarklet'};};var d=document,s=d.createElement('script');s.setAttribute('src','https://hypothes.is/embed.js');d.body.appendChild(s)})();"""
)
config.bind('<alt-shift-n>', """:open https://via.hypothes.is/{url}""")

# I tend to press those by mistake
config.unbind('<ctrl-a>', mode='normal')
config.unbind('<ctrl-x>', mode='normal')
