[user]
email = "konubinixweb@gmail.com"
name = "Samuel Loury"

[signing]
behavior = "own"
backend  = "gpg"
key      = "konubinix"

[revset-aliases]
"mine_deps()" = "bookmarks() ~ (mine | trunk())"

[aliases]
update-mine = ["rebase", "-r", "mine", "-d", "mine_deps()"]
