# [[id:2b1bd642-8cac-4fba-8bdc-f139504bc586][config:1]]
[revset-aliases]
"mine_deps()" = "bookmarks() ~ (mine | trunk())"
"dangling()" = "all() ~ (ancestors(bookmarks() | remote_bookmarks() | tags() | @) | root())"
[aliases]
update-mine = ["rebase", "-r", "mine", "-o", "mine_deps()"]
all = ["logs", "-r", "all()"]
watch = ["util", "exec", "--", "bash", "-c", 'd=$(mktemp -d); trap "rm -rf $d" EXIT; JJ_WATCH_DIR=$d viddy --differences --interval 100ms --exec bash /home/sam/perso/perso/bin/jj_watch_log.sh']
cleandangling = ["abandon", "-r", "dangling()"]
# config:1 ends here
