#!/bin/bash

_parse_help_candidates ()
{
    local cur prev words cword split
    _init_completion || return
    if [[ "$cur" == -* ]]; then
        local opts=$( _parse_help "$1" )
        COMPREPLY=( $( compgen -W "$opts" -- "$cur" ) )
        return 0
    fi
}

_konix_load_completions()
{
    local bin dir bin_basename
    bin="${1}"
    dir="${2}"
    bin_basename="${bin##*/}"
    # override with my local one if possible
    local compfile="${dir}/bash-completion/${bin_basename}"

    # Avoid trying to source dirs; https://bugzilla.redhat.com/903540
    [[ -f "$compfile" ]] && . "$compfile" &>/dev/null && return 124
}

_konix_completion_loader()
{
    # use the system wide completion
    _completion_loader "$@"
    local res="$?"

    _konix_load_completions "$1" "${KONIX_CONFIG_DIR}"
    _konix_load_completions "$1" "${KONIX_PERSO_CONFIG_DIR}"
    _konix_load_completions "$1" "${KONIX_PERSO_HOST_CONFIG_DIR}"
    # Propagate the result of the system completion
    return "${res}"
} &&
complete -D -F _konix_completion_loader
