#!/bin/bash
# -*- mode: sh -*-
# set -x
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

python "${KONIX_DEVEL_DIR}/bin/konix_check_env"

# ####################################################################################################
# Get the pwd, without paying attention to the given PWD because it may be wrong
# ####################################################################################################
export PWD="$(pwd)"

# ####################################################################################################
# Readline
# ####################################################################################################
if ! on_windows_p.sh
then
    # this supposed that GNU stty is installed and that the special chars are the same on your terminal as on mine
    # undef C-s and C-r  I don't like C-s to stop my terminal, and find it more usefull for incremental search
	stty stop undef
	stty rprnt undef
    #undef C-w , readline automagically binds the special terminal chars to their equivalent commands
	stty werase undef
fi

# ####################################################################################################
# Personal info
# ####################################################################################################
if [ -f "$KONIX_PERSO_DIR/perso" ]; then
	source "$KONIX_PERSO_DIR/perso"
fi

# ################################################################################
# Aliases
# ################################################################################
# Take the aliases from a special file
if [ -f "$KONIX_CONFIG_DIR/bash_aliases" ]; then
	source "$KONIX_CONFIG_DIR/bash_aliases"
fi

# ################################################################################
# Importation de mes fonctions persos
# ################################################################################
source "${KONIX_LIB_DIR}/lib_bash.sh"

# ######################################################################
# Bash completion custom
# ######################################################################
# load the bash completion script
source_if_possible "/usr/share/bash-completion/bash_completion"
# makej alias
source_if_possible "/usr/share/bash-completion/completions/make"
complete -F _make makej
# get the aptitude completion from sjoubert repository
source_if_possible "$KONIX_DEVEL_DIR/sjoubert_dot_rc/.config/bash/completions/aptitude"

# Log sur l'agent SSH
if is_on_linux
then
	gpg_agent_start_KONIX
	GPG_TTY=$(tty)
    export GPG_TTY
fi
