#!/bin/bash
# -*- mode: sh -*-
# set -x
# If not running interactively, don't do anything
[ -z "$PS1" ] && return

"${KONIX_DEVEL_DIR}/bin/konix_check_env"
# ####################################################################################################
# Get the pwd, without paying attention to the given PWD because it may be wrong
# ####################################################################################################
export PWD="$(pwd)"

# ####################################################################################################
# Readline
# ####################################################################################################
if ! on_windows_p.sh
then
    # this supposed that GNU stty is installed and that the special chars are the same on your terminal as on mine
    # undef C-s and C-r  I don't like C-s to stop my terminal, and find it more usefull for incremental search
	stty stop undef
	stty rprnt undef
    #undef C-w , readline automagically binds the special terminal chars to their equivalent commands
	stty werase undef
fi

# ####################################################################################################
# Personal info
# ####################################################################################################
if [ -f "${KONIX_PERSO_DIR}/${HOSTNAME}/shrc" ]; then
	source "${KONIX_PERSO_DIR}/${HOSTNAME}/shrc"
fi

# ################################################################################
# Aliases
# ################################################################################
# Take the aliases from a special file
if [ -f "$KONIX_CONFIG_DIR/bash_aliases" ]; then
	source "$KONIX_CONFIG_DIR/bash_aliases"
fi
# ################################################################################
# Import my custom functions
# ################################################################################
source "${KONIX_LIB_DIR}/lib_bash.sh"
# In interactive mode, I also want colors
source "${KONIX_LIB_DIR}/colors.sh"

# Log sur l'agent SSH
if is_on_linux
then
	konix_gpg_use
	GPG_TTY=$(tty)
    export GPG_TTY
fi
