{
  inputs = {
    nixpkgs.url = "nixpkgs";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs =
    {
      self,
      nixpkgs,
      flake-utils,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = import nixpkgs { inherit system; };
      in
      {
        packages.default = pkgs.yt-dlp.overridePythonAttrs (old: rec {
          version = "2026.08.18.122307";
          src = pkgs.fetchFromGitHub {
            owner = "yt-dlp";
            repo = "yt-dlp";
            rev = "5d5b634d8";
            hash = "sha256-s4Egvjfwj6F4iCN0y+Ax5xAg5Cuh+0qGMtBQe3NlBck=";
          };
          # version.py is autogenerated at release time, so a mid-cycle commit
          # still claims to be the last stable. Make it dump the real version.
          postPatch = (old.postPatch or "") + ''
            substituteInPlace yt_dlp/version.py \
              --replace-fail "__version__ = '2026.07.04'" "__version__ = '${version}'" \
              --replace-fail "_pkg_version = '2026.07.04'" "_pkg_version = '${version}'" \
              --replace-fail "RELEASE_GIT_HEAD = '997fa140840a08df3938b40da470c78049fef1f6'" "RELEASE_GIT_HEAD = '${src.rev}'" \
              --replace-fail "VARIANT = None" "VARIANT = 'nightly'" \
              --replace-fail "CHANNEL = 'stable'" "CHANNEL = 'nightly'" \
              --replace-fail "ORIGIN = 'yt-dlp/yt-dlp'" "ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'"
          '';
          doCheck = false;
        });
      }
    );
}
